// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByX-FLptmiHHDBWfiJdFk8P0dhgTny10Y',
    appId: '1:363306107956:web:b62a3341aa97f8de117661',
    messagingSenderId: '363306107956',
    projectId: 'easy-bite-4d3c6',
    authDomain: 'easy-bite-4d3c6.firebaseapp.com',
    storageBucket: 'easy-bite-4d3c6.appspot.com',
    measurementId: 'G-72FLGW1CXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJpPlwUHR64aZ3IvzmTYRMgId7X96W6HY',
    appId: '1:363306107956:android:0bb1be0f24c48b3f117661',
    messagingSenderId: '363306107956',
    projectId: 'easy-bite-4d3c6',
    storageBucket: 'easy-bite-4d3c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrCaAEG5X-0IE2TAh1qFVO5UfI30iqM7w',
    appId: '1:363306107956:ios:7a8b77685fc37475117661',
    messagingSenderId: '363306107956',
    projectId: 'easy-bite-4d3c6',
    storageBucket: 'easy-bite-4d3c6.appspot.com',
    iosBundleId: 'com.easybite.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrCaAEG5X-0IE2TAh1qFVO5UfI30iqM7w',
    appId: '1:363306107956:ios:7a8b77685fc37475117661',
    messagingSenderId: '363306107956',
    projectId: 'easy-bite-4d3c6',
    storageBucket: 'easy-bite-4d3c6.appspot.com',
    iosBundleId: 'com.easybite.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByX-FLptmiHHDBWfiJdFk8P0dhgTny10Y',
    appId: '1:363306107956:web:1a2da4e7e57212cc117661',
    messagingSenderId: '363306107956',
    projectId: 'easy-bite-4d3c6',
    authDomain: 'easy-bite-4d3c6.firebaseapp.com',
    storageBucket: 'easy-bite-4d3c6.appspot.com',
    measurementId: 'G-V18ESCB7WS',
  );
}
